# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/MyRCA.xdc

# Block Designs: bd/RCA_Test/RCA_Test.bd
# Block Designs: The module: 'RCA_Test' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: bd/RCA_Test/ip/RCA_Test_RCA_0_0/RCA_Test_RCA_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RCA_Test_RCA_0_0 || ORIG_REF_NAME==RCA_Test_RCA_0_0} -quiet] -quiet

# IP: bd/RCA_Test/ip/RCA_Test_RCA_0_1/RCA_Test_RCA_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RCA_Test_RCA_0_1 || ORIG_REF_NAME==RCA_Test_RCA_0_1} -quiet] -quiet

# IP: bd/RCA_Test/ip/RCA_Test_RCA_0_2/RCA_Test_RCA_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RCA_Test_RCA_0_2 || ORIG_REF_NAME==RCA_Test_RCA_0_2} -quiet] -quiet

# XDC: e:/DSD/Projects/RCA_Test/RCA_Test.gen/sources_1/bd/RCA_Test/RCA_Test_ooc.xdc
